language: python
python:
    - 2.7.8
    - 2.7
    - pypy
    - 3.3
    - 3.4
    - 3.5
    - nightly
    - pypy3

script:
     - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then python -m unittest discover; fi